#!/usr/bin/env python

import sys
import vobject

def parseAndWrite(instream, outstream):
  for card in vobject.readComponents(instream):
    if not 'email' in card.contents:
      continue

    nickname = u''
    if 'nickname' in card.contents:
      nickname = card.nickname.value
    if len(nickname) == 0:
      nickname = card.email.value.split(u'@')[0]
    nickname = nickname.lower()
    line = u' '.join([u"alias", nickname, card.fn.value, u'<'+card.email.value+u'>']) + u"\n"
    outstream.write(line.encode('utf-8'))


with open(sys.argv[1], 'rt') as sourcefile:
  with open(sys.argv[2], 'wt') as destfile:
    parseAndWrite(sourcefile, destfile)
