#!/usr/bin/env python

import sys
import vobject

def parseAndWrite(instream, outstream):
  for card in vobject.readComponents(instream, outstream):
    if not 'tel' in card.contents:
      continue
    for tel in card.contents['tel']:
      line = u','.join([card.fn.value, tel.value]) + u"\n"
      outstream.write(line.encode('utf-8'))


with open(sys.argv[1], 'rt') as sourcefile:
  with open(sys.argv[2], 'wt') as destfile:
    parseAndWrite(sourcefile, destfile)
